# Generated by Django 3.1.3 on 2021-10-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_modify_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='team',
            field=models.CharField(max_length=20),
        ),
    ]
