# Generated by Django 3.1.3 on 2021-10-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20211008_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('home_team', models.CharField(max_length=20)),
                ('away_team', models.CharField(max_length=20)),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
            ],
        ),
    ]
