# Generated by Django 3.1.3 on 2021-10-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_calender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calender',
        ),
    ]
