# Generated by Django 3.1.3 on 2021-10-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20211017_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_url',
            field=models.TextField(null=True),
        ),
    ]
