# Generated by Django 3.1.7 on 2021-11-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.TextField(db_column='_id', primary_key=True, serialize=False)),
                ('date', models.CharField(db_column='date', max_length=50)),
                ('state_game', models.CharField(db_column='state_game', max_length=50)),
                ('home', models.CharField(db_column='home', max_length=50)),
                ('home_score', models.CharField(db_column='home_score', max_length=50)),
                ('home_result', models.CharField(db_column='home_result', max_length=50)),
                ('home_time', models.CharField(db_column='home_time', max_length=50)),
                ('away', models.CharField(db_column='away', max_length=50)),
                ('away_score', models.CharField(db_column='away_score', max_length=50)),
                ('away_result', models.CharField(db_column='away_result', max_length=50)),
                ('away_time', models.CharField(db_column='away_time', max_length=50)),
                ('stadium', models.CharField(db_column='stadium', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
