# Generated by Django 3.1.7 on 2021-11-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211118_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.TextField(db_column='_id', primary_key=True, serialize=False)),
                ('team_id', models.CharField(db_column='team_id', max_length=50)),
                ('team_name', models.CharField(db_column='team_name', max_length=50)),
                ('team_code', models.CharField(db_column='team_code', max_length=50)),
                ('team_img', models.CharField(db_column='team_img', max_length=50)),
                ('team_stadium', models.CharField(db_column='team_stadium', max_length=50)),
            ],
            options={
                'db_table': 'teams',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='matches',
            options={'managed': False},
        ),
    ]
